CREATE TABLE orders (
    id VARCHAR(100) PRIMARY KEY,
    account_id VARCHAR(100) NOT NULL,
    asset VARCHAR(100) NOT NULL,
    side VARCHAR(20) NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    executed_at TIMESTAMP WITH TIME ZONE
);